#version: "3.9"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: deccan-backend
    command: gunicorn deccenindiaweb_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: deccan-frontend
    ports:
      - "80:80"
    env_file:
      - ./Frontend/dist/.env
    depends_on:
      - backend
    restart: always
